---
title: "IBM employees predictions"
author: "Karol Roszak"
date: "5/5/2021"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r imports, echo=FALSE, message=FALSE, warning=FALSE}
library(knitr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(reactable)
library(plyr)

set.seed(05052021)
```


# Reading and preprocessing 

### Reading raw data

```{r reading_data, echo=TRUE}
# Reading raw data and entry preprocessing

raw_data = read.csv("data/raw_data.csv")
raw_data = na.omit(raw_data) # strict policy for missing values

# Reshaping raw data and saving it to inspect in Weka

raw_weka_data = raw_data %>% relocate(Attrition, .after=YearsWithCurrManager)
write.csv(raw_weka_data, "data/raw_weka_data.csv", row.names = FALSE)

# Raw data visualization to check out attribute values and their features

  # in Weka maybe......
```

```{r first_glance, echo=FALSE, warning=F}

# Having first glance at each of the attributes... either here or graphics from Weka.........




#attributes(raw_weka_data)

#check = summary(raw_weka_data)
#check




######
#a = raw_weka_data %>% select(col_names[1])
#ve = unlist(a, use.names = FALSE)
#ve

#mean(ve)
#sd(ve)


col_names = names(raw_weka_data)
#col_names
#col_names[1]

i = 0
for(i in 1:35){

considered_column = raw_weka_data %>% select(col_names[i])
considered_column_vals = unlist(considered_column, use.names = FALSE)

  
plot_g =ggplot(raw_weka_data, aes_string(x = col_names[i])) +
          geom_histogram(stat = 'count', aes(fill=Attrition)) +
          geom_vline(xintercept = mean(considered_column_vals), linetype="dotted", size = 1, color = 'black') +
          geom_vline(xintercept = mean(considered_column_vals) + 3 * sd(considered_column_vals), linetype="dotted",  size = 1, color = 'green') +
          geom_vline(xintercept = mean(considered_column_vals) - 3 * sd(considered_column_vals), linetype="dotted",  size = 1, color = 'green') +
          scale_fill_brewer(palette = 'Set1') +
          theme_bw()

#geom_ribbon( aes(xmin = mean(considered_column_vals) - 3 * sd(considered_column_vals), xmax= mean(considered_column_vals) + 3 * sd(considered_column_vals), ymin = 0, ymax = 20, fill = Attrition), alpha=0.03) +

plot(plot_g)
}

```
### Data preprocessing

```{r preprocessing, echo=TRUE}
# Dropping irrelevant attributes

preprocessed_data = raw_weka_data %>%
  select(-EmployeeCount) %>%
  select(-EmployeeNumber) %>%
  select(-Over18) %>%
  select(-StandardHours)

# Discretizing some attributes

preprocessed_data = preprocessed_data %>% 
  mutate(Education=recode(Education,
                                 `1` = 'Below College',
                                 `2` = 'College',
                                 `3` = 'Bachelor',
                                 `4` = 'Master',
                                 `5` = 'Doctor')) %>%
  mutate(EnvironmentSatisfaction = recode(EnvironmentSatisfaction,
                                 `1` = 'Low',
                                 `2` = 'Medium',
                                 `3` = 'High',
                                 `4` = 'Very High')) %>%
  mutate(JobInvolvement = recode(JobInvolvement,
                                 `1` = 'Low',
                                 `2` = 'Medium',
                                 `3` = 'High',
                                 `4` = 'Very High')) %>%
  mutate(JobSatisfaction = recode(JobSatisfaction,
                                  `1` = 'Low',
                                 `2` = 'Medium',
                                 `3` = 'High',
                                 `4` = 'Very High')) %>%
  mutate(PerformanceRating = recode(PerformanceRating,
                                 `1` = 'Low',
                                 `2` = 'Good',
                                 `3` = 'Excellent',
                                 `4` = 'Outstanding')) %>%
  mutate(RelationshipSatisfaction = recode(RelationshipSatisfaction,
                                 `1` = 'Low',
                                 `2` = 'Medium',
                                 `3` = 'High',
                                 `4` = 'Very High')) %>%
  mutate(WorkLifeBalance = recode(WorkLifeBalance,
                                 `1` = 'Bad',
                                 `2` = 'Good',
                                 `3` = 'Better',
                                 `4` = 'Best'))

write.csv(preprocessed_data, "data/preprocessed_data.csv", row.names = FALSE)
```


```{r preprocessed_data_presentation}

# just a temporary table.....

#preprocessed_table = reactable(preprocessed_data, 
#      defaultColDef = colDef(
#      header = function(value) gsub(".", " ", value, fixed = TRUE),
#      cell = function(value) format(value),
#      align = "center",
#      headerStyle = list(background = "#edf8fb")
#    ),
#    defaultPageSize = 5,
#    bordered = TRUE,
#    highlight = TRUE,
#    filterable = TRUE,
#    searchable = TRUE,
#    resizable = TRUE
#    )

#preprocessed_table
#just a little change to test git account...

```

# Finding correlations in data

```{r}

```


```{r}

```


```{r}

```

# Taking care of outliers in data

```{r}

```


```{r}

```

```{r}

```

























